jwt:
  issuer: roommate-app
  secret: ${JWT_SECRET_KEY}
  access-ttl-seconds:  600     # 10분
  refresh-ttl-seconds: 604800 # 7일
spring:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 123
  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
